INSERT INTO ships (ship_name, ship_size, guest_rating) VALUES ('Intchantment of the Seas', 2500, 4.9);
INSERT INTO ships (ship_name, ship_size, guest_rating) VALUES ('Double Paradise', 1800, 4.3);
INSERT INTO ships (ship_name, ship_size, guest_rating) VALUES ('Long Voyager', 2000, 4.2);
INSERT INTO ships (ship_name, ship_size, guest_rating) VALUES ('Costa Corta', 800, 4.2);
INSERT INTO ships (ship_name, ship_size, guest_rating) VALUES ('Floating Oasis', 3000, 4.8);
INSERT INTO ships (ship_name, ship_size, guest_rating) VALUES ('ByteTanic', 4000, 4.7);
INSERT INTO ships (ship_name, ship_size, guest_rating) VALUES ('Charming Sea Princess', 1200, 4.1);
INSERT INTO ships (ship_name, ship_size, guest_rating) VALUES ('True Beauty', 2400, 0.0);

INSERT INTO itineraries (ship_id, num_days, num_ports) VALUES (1, 5, 2);
INSERT INTO itineraries (ship_id, num_days, num_ports) VALUES (1, 10, 4);
INSERT INTO itineraries (ship_id, num_days, num_ports) VALUES (2, 5, 2);
INSERT INTO itineraries (ship_id, num_days, num_ports) VALUES (2, 7, 3);
INSERT INTO itineraries (ship_id, num_days, num_ports) VALUES (3, 5, 2);
INSERT INTO itineraries (ship_id, num_days, num_ports) VALUES (3, 7, 2);
INSERT INTO itineraries (ship_id, num_days, num_ports) VALUES (4, 10, 2);
INSERT INTO itineraries (ship_id, num_days, num_ports) VALUES (4, 10, 3);
INSERT INTO itineraries (ship_id, num_days, num_ports) VALUES (4, 10, 4);
INSERT INTO itineraries (ship_id, num_days, num_ports) VALUES (5, 5, 1);
INSERT INTO itineraries (ship_id, num_days, num_ports) VALUES (5, 5, 2);
INSERT INTO itineraries (ship_id, num_days, num_ports) VALUES (6, 5, 2);
INSERT INTO itineraries (ship_id, num_days, num_ports) VALUES (6, 7 ,3);
INSERT INTO itineraries (ship_id, num_days, num_ports) VALUES (6, 10, 4);
INSERT INTO itineraries (ship_id, num_days, num_ports) VALUES (7, 7, 2);
INSERT INTO itineraries (ship_id, num_days, num_ports) VALUES (7, 7, 3);
INSERT INTO itineraries (ship_id, num_days, num_ports) VALUES (8, 5, 2);
INSERT INTO itineraries (ship_id, num_days, num_ports) VALUES (8, 10, 3);

INSERT INTO ports (port_abbr, port_location) VALUES ('COM', 'Costa Maya, Mexico');
INSERT INTO ports (port_abbr, port_location) VALUES ('COZ', 'Cozumel, Mexico');
INSERT INTO ports (port_abbr, port_location) VALUES ('NAS', 'Nassau, Bahamas');
INSERT INTO ports (port_abbr, port_location) VALUES ('SJN', 'San Juan, Puerto Rico');
INSERT INTO ports (port_abbr, port_location) VALUES ('KYW', 'Key West, Florida');
INSERT INTO ports (port_abbr, port_location) VALUES ('HAV', 'Havana, Cuba');
INSERT INTO ports (port_abbr, port_location) VALUES ('GRC', 'Grand Cayman, Cayman Islands');
INSERT INTO ports (port_abbr, port_location) VALUES ('MNB', 'Montego Bay, Jamaica');
INSERT INTO ports (port_abbr, port_location) VALUES ('STS', 'St. Thomas, Virgin Islands');
INSERT INTO ports (port_abbr, port_location) VALUES ('STK', 'St. Kitts, Virgin Islands');
INSERT INTO ports (port_abbr, port_location) VALUES ('LAB', 'Labadee, Haiti');
INSERT INTO ports (port_abbr, port_location) VALUES ('STD', 'Santo Domingo, Dominican Republic');
INSERT INTO ports (port_abbr, port_location) VALUES ('ORJ', 'Oranjedast, Aruba');
INSERT INTO ports (port_abbr, port_location) VALUES ('ROT', 'Roatan, Honduras');

INSERT INTO excursions (port_id, excursion_name, exertion_level, adult_price, child_price) VALUES (7, 'Snorkling', 'Moderate', 70.00, 45.00);
INSERT INTO excursions (port_id, excursion_name, exertion_level, adult_price, child_price) VALUES (14, 'Birds of Paradise Tour', 'Low', 30.00, 10.00);
INSERT INTO excursions (port_id, excursion_name, exertion_level, adult_price, child_price) VALUES (3, 'Water Park', 'Moderate', 70.00, 45.00);
INSERT INTO excursions (port_id, excursion_name, exertion_level, adult_price, child_price) VALUES (6, 'Horse Back Riding', 'Moderate', 60.00, 40.00);
INSERT INTO excursions (port_id, excursion_name, exertion_level, adult_price, child_price) VALUES (7, 'Parasailing', 'High', 220.00, 170.00);
INSERT INTO excursions (port_id, excursion_name, exertion_level, adult_price, child_price) VALUES (14, 'Dolphin Swim', 'Moderate', 250.00, 250.00);
INSERT INTO excursions (port_id, excursion_name, exertion_level, adult_price, child_price) VALUES (12, 'Mountain Climbing', 'High', 200.00, 150.00);
INSERT INTO excursions (port_id, excursion_name, exertion_level, adult_price, child_price) VALUES (5, 'Scuba Diving', 'High', 300.00, 250.00);
INSERT INTO excursions (port_id, excursion_name, exertion_level, adult_price, child_price) VALUES (9, 'Beach Day', 'low', 40.00, 20.00);
INSERT INTO excursions (port_id, excursion_name, exertion_level, adult_price, child_price) VALUES (4, 'Shopping Day', 'low', 0.00, 0.00);
INSERT INTO excursions (port_id, excursion_name, exertion_level, adult_price, child_price) VALUES (1, 'Hiking', 'High', 30.00, 10.00);
INSERT INTO excursions (port_id, excursion_name, exertion_level, adult_price, child_price) VALUES (2, 'Four Wheeling', 'Moderate', 80.00, 80.00);
INSERT INTO excursions (port_id, excursion_name, exertion_level, adult_price, child_price) VALUES (8, 'Zip Line', 'Moderate', 60.00, 40.00);
INSERT INTO excursions (port_id, excursion_name, exertion_level, adult_price, child_price) VALUES (10, 'Aquarium', 'Low', 70.00, 45.00);
